<?php /** @var AKisilenko\ModuleLesson6\Block\Requests $block */ ?>
<?php /** @var Magento\Framework\View\TemplateEngine\Php $this */ ?>
<table>
    <tr>
        <th><?php echo __('Date'); ?></th>
        <th><?php echo __('Comment'); ?></th>
        <th><?php echo __('Status'); ?></th>
    </tr>

    <?php foreach($block->getMySampleRequests() as $sampleRequest): ?>
        <tr>
            <td><?php echo $this->escapeHtml($sampleRequest->getCreatedAt()) ?></td>
            <td><?php echo $this->escapeHtml($sampleRequest->getComment()) ?></td>
            <td><?php echo $this->escapeHtml($sampleRequest->getStatus()) ?></td>
        </tr>
    <?php endforeach; ?>
</table>