<div id="ask-text" data-bind="scope:'ask_question_text'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#ask-text": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ask_question_text": {
                        "component": "AKisilenko_UIModuleLesson9/js/ask_question_text",
                        "template" : "AKisilenko_UIModuleLesson9/text_template",
                        "question" : "<?php echo $block->getQuestion();?>"
                    }
                }
            }
        }
    }
    </script>
</div>